// Upload model file

export const UPLOAD_MODEL_FILE_REQUEST = 'UPLOAD_MODEL_FILE_REQUEST'
export const UPLOAD_MODEL_FILE_FAILURE = 'UPLOAD_MODEL_FILE_FAILURE'
export const UPLOAD_MODEL_FILE_SUCCESS = 'UPLOAD_MODEL_FILE_SUCCESS'
export const UPLOAD_MODEL_FILE = 'UPLOAD_MODEL_FILE'

// Layers

export const TOGGLE_LAYER = 'TOGGLE_LAYER'
export const SELECT_ALL_LAYERS = 'SELECT_ALL_LAYERS'
export const DESELECT_ALL_LAYERS = 'DESELECT_ALL_LAYERS'
